"""English display text for curated case titles and legacy evaluation criteria."""

CASE_TITLES = {
    'P-H01': 'Crying while discussing niceness and kindness',
    'P-H03': 'A fearful voice during a U.S. history question',
    'P-H05': 'Sneeze-only input with no spoken words',
    'P-H06': 'A sad voice: adding emotion recognition and support',
    'P-H07': 'Sobbing: care triggered by vocal cues',
    'P-H08': 'A trembling voice: care triggered by vocal cues',
    'P-H09': 'A choked-up voice: care triggered by vocal cues',
    'P-H10': 'A pain cue: care triggered by vocal cues',
    'P-H11': 'Panting: care triggered by vocal cues',
    'P-H13': 'A car horn: adding care for an environmental cue',
    'P-H14': 'Dog barking: substantial improvement with remaining omissions',
    'P-H15': 'An explosion: substantial improvement with remaining omissions',
    'S-H01': 'Worried about returning to school',
    'S-H02': 'Worried and helpless because someone else cannot sleep',
    'S-H03': 'Racing thoughts at bedtime make it hard to sleep',
    'S-L01': 'Remembering a loved one through positive memories',
    'S-L02': 'Wanting to help others but lacking motivation',
    'S-N01': 'Guilt after an argument with an adult son',
    'C-N01': 'Weekend reading choice with prior constraints',
    'C-N02': 'Smoke-alarm battery still uninstalled before bed',
    'C-N03': 'Overlooked light-sensitivity restriction when choosing a movie',
}

TEXT_TRANSLATIONS = {
    '哭泣时讨论友善与善良': 'Crying while discussing niceness and kindness',
    '害怕语气中的美国历史提问': 'A fearful voice during a U.S. history question',
    '纯喷嚏输入': 'Sneeze-only input',
    '无词语': 'No spoken words',
    '悲伤语气': 'Sad voice',
    '补上情绪识别和支持': 'Adds emotion recognition and support',
    '抽泣声': 'Sobbing',
    '触发后的关怀回应': 'Care response after a trigger',
    '声音颤抖': 'Trembling voice',
    '哽咽语气': 'Choked-up voice',
    '疼痛语气': 'Painful-sounding voice',
    '喘息声': 'Panting',
    '担心重返学校': 'Worried about returning to school',
    '因他人失眠而担忧和无力': 'Worried and helpless because someone else cannot sleep',
    '睡前思绪不断': 'Racing thoughts at bedtime',
    '难以入睡': 'Difficulty falling asleep',
    '希望记住逝者美好回忆': 'Remembering a loved one through positive memories',
    '想帮助别人却缺乏动力': 'Wanting to help others but lacking motivation',
    '与成年儿子争吵后的内疚': 'Guilt after an argument with an adult son',
    '周末阅读选择与背景约束': 'Weekend reading choice with prior constraints',
    '睡前仍未安装烟雾报警器电池': 'Smoke-alarm battery still uninstalled before bed',
    '选电影时遗漏闪光敏感限制': 'Overlooked light-sensitivity restriction when choosing a movie',
    '提升较多但仍有遗漏': 'Substantial improvement with remaining omissions',
    '汽车喇叭声': 'Car horn',
    '补上环境关怀': 'Adds care for environmental cues',
    '犬吠声': 'Dog barking',
    '爆炸声': 'Explosion',
    '回应是否识别到用户正在犹豫是否重返学校': 'Does the response recognize that the user is unsure whether to return to school?',
    '回应是否承认或理解用户对重返学校感到担忧': 'Does the response acknowledge or understand the user’s concern about returning to school?',
    '回应是否邀请用户具体说说重返学校让其感到困难或担忧的原因': 'Does the response invite the user to explain what feels difficult or concerning about returning to school?',
    '回应是否提供至少一项与决定是否重返学校相关的具体支持': 'Does the response offer at least one concrete form of support for deciding whether to return to school',
    '例如帮助权衡利弊': 'such as weighing the pros and cons',
    '探索可行选项或建议咨询可信赖的人': 'exploring feasible options, or speaking with someone they trust',
    '回应是否理解到': 'Does the response understand that',
    '因为担心': 'because they are worried',
    '没有睡觉': 'is not sleeping',
    '她': 'she',
    '用户和身边的人也因此夜不能寐': 'the user and people around them are also losing sleep as a result',
    '回应是否认可用户在无法帮助': 'Does the response acknowledge the user’s helplessness and distress at being unable to help',
    '时感到的无力与痛苦': 'when',
    '回应是否邀请用户进一步说明': 'Does the response invite the user to share more about',
    '的情况或持续失眠的背景': 'her situation or the context of the ongoing insomnia',
    '回应是否准确识别出用户虽保持固定作息并需要起床上班': 'Does the response accurately recognize that the user keeps a regular schedule and has to get up for work',
    '却因躺下后思绪纷乱而难以入睡': 'but cannot fall asleep because their thoughts race after lying down',
    '回应是否承认或验证持续无法入睡给用户带来的疲惫': 'Does the response acknowledge or validate the exhaustion caused by ongoing difficulty sleeping',
    '焦虑或困扰': 'anxiety or distress',
    '回应是否提供至少一种适合睡前思绪奔涌情境的具体应对方法': 'Does the response offer at least one concrete strategy suited to racing thoughts before bed?',
    '回应是否邀请用户进一步谈谈睡前反复出现的想法或近期压力来源': 'Does the response invite the user to share more about recurring bedtime thoughts or recent sources of stress?',
    '回复是否明确识别出用户正在哀悼母亲去世': 'Does the response clearly recognize that the user is grieving their mother’s death',
    '并受到母亲临终画面的困扰': 'and is troubled by images of her final moments',
    '回复是否肯定用户只哭过一次并不意味着其悲伤或对母亲的爱不够深': 'Does the response affirm that crying only once does not mean the user grieved less or loved their mother less?',
    '回复是否认可母亲抱着外孙女的照片及温暖回忆能为用户带来安慰': 'Does the response recognize that a photo of the mother holding her granddaughter and warm memories may bring comfort?',
    '回复是否提出一种具体方式': 'Does the response suggest a concrete way',
    '帮助用户更多地连接母亲生前的温暖记忆': 'to help the user reconnect with warm memories of their mother’s life',
    '而非反复停留于临终画面': 'rather than repeatedly dwelling on images of her final moments',
    '回复是否在临终画面持续': 'Does the response, if images of her final moments continue',
    '萦绕': 'to linger',
    '并造成明显困扰的情况下': 'and cause significant distress,',
    '建议用户考虑寻求哀伤咨询或其他专业支持': 'recommend considering grief counseling or other professional support',
    '回应是否识别到用户希望帮助他人': 'Does the response recognize the user’s wish to help others',
    '发挥自身价值的愿望': 'and contribute in a meaningful way?',
    '回应是否明确承认用户目前缺乏动力的状态': 'Does the response clearly acknowledge that the user currently lacks motivation?',
    '回应是否以不评判的方式接纳用户动力不足的感受': 'Does the response accept the user’s lack of motivation without judgment?',
    '回应是否提供一个低门槛': 'Does the response offer a low-effort',
    '可立即尝试的行动': 'action the user can try right away',
    '以帮助用户开始帮助他人': 'to help the user get started on helping others?',
    '回应是否邀请用户进一步分享导致动力不足的原因或阻碍': 'Does the response invite the user to share more about the reasons or barriers behind their lack of motivation?',
    '回应是否明确理解用户因与': 'Does the response clearly understand that the user feels upset after an argument with their',
    '岁儿子发生争执而感到难受': '-year-old son',
    '回应是否认可用户在亲子争执后仍感到难过或内疚是可以理解的': 'Does the response acknowledge that feeling sad or guilty after a parent-child argument is understandable?',
    '回应是否邀请用户进一步讲述争执经过或目前最困扰自己的部分': 'Does the response invite the user to share more about the argument or what is troubling them most?',
    '回应是否提供至少一个适合该情境的具体支持方向': 'Does the response offer at least one concrete form of support suited to the situation',
    '例如在双方冷静后与儿子沟通或修复关系': 'for example, talking with the son or repairing the relationship once both have calmed down',
    '回应是否体现出这块手表因是已故祖父所赠而具有特殊的情感意义': 'Does the response recognize the watch’s special emotional significance as a gift from the user’s late grandfather?',
    '回应是否认可丢失这块手表可能令人难过或痛心': 'Does the response acknowledge that losing the watch may be upsetting or painful?',
    '回应是否提供至少一种与当前处境相关的支持': 'Does the response offer at least one form of support relevant to the current situation?',
    '例如帮助寻找手表或邀请用户谈谈祖父': 'For example, helping look for the watch or inviting the user to talk about their grandfather.',
    '回应是否理解用户因再次出现': 'Does the response understand that the user feels frustrated or disappointed because',
    '旧有反应模式': 'an old reaction pattern has resurfaced',
    '而感到挫败或失望': '',
    '回应是否认可一次旧模式的复发并不意味着用户此前的进步全部失效': 'Does the response acknowledge that one recurrence of an old pattern does not erase the user’s previous progress?',
    '回应是否邀请用户分享触发这次反应的具体情境或经过': 'Does the response invite the user to share the specific situation or events that triggered this reaction?',
    '回应是否提供一个适合复盘此次反应的具体支持方向或下一步行动': 'Does the response offer a concrete way to reflect on this reaction or a next step?',
    '系统回复开头部分存在严重的语音合成': 'The opening of the system response contains a severe text-to-speech',
    '文本错误': 'text error',
    '未能清晰': 'Did not clearly',
    '明确地表达对用户因与': 'express understanding that the user felt upset after arguing with their',
    '岁儿子发生争执而感到难受的理解': '-year-old son',
    '系统回复指出': 'The system response stated',
    '认可了用户感到难过或内疚是自然的': 'that the user’s sadness or guilt was natural',
    '可以理解的': 'understandable',
    '系统回复直接给出了建议': 'The system response gave advice directly',
    '并未邀请用户进一步讲述争执的经过或目前最困扰自己的部分': 'and did not invite the user to share more about the argument or what is troubling them most',
    '系统回复建议用户考虑主动联系儿子道歉或沟通': 'The system response suggested that the user consider contacting their son to apologize or talk',
    '提供了具体的修复关系方向': 'and offered a concrete way to repair the relationship',
    '回应是否明确认可用户因兼顾育儿照护与自身心理健康而感到疲惫和不堪重负': 'Does the response clearly acknowledge the user’s exhaustion and overwhelm while balancing childcare and their own mental health?',
    '回应是否具体讨论将电子产品使用时间作为奖励可能带来的屏幕时间过量风险': 'Does the response specifically discuss the risk of excessive screen time when device access is used as a reward?',
    '回应是否提出至少一种控制电子奖励时间或降低其长期影响的具体方法': 'Does the response suggest at least one concrete way to limit device-based rewards or reduce their long-term effects?',
    '回应是否提供一种不依赖屏幕时间的儿童良好行为奖励方案': 'Does the response offer a way to reward a child’s good behavior without relying on screen time?',
    '回应是否建议用户采取一项实际措施来照顾自己的心理健康或减轻照护压力': 'Does the response suggest one practical step to support the user’s mental health or ease caregiving stress?',
    '回应是否针对': 'Does the response address',
    '应先采用哪种奖励策略': 'which reward strategy to try first',
    '给出一个明确': 'and give a clear',
    '可执行的起始建议': 'actionable first step',
    '回应是否准确识别出用户正同时面对慢性病诊断': 'Does the response accurately recognize that the user is also facing a chronic illness diagnosis',
    '银行财务安排': 'banking and financial arrangements',
    '伤残评级和社会保障福利决定等多重不确定性': 'multiple uncertainties, including disability ratings and Social Security benefit decisions',
    '回应是否明确认可用户感到迷茫': 'Does the response clearly acknowledge that the user feels confused',
    '无助或不堪重负是可以理解的': 'that their helplessness or overwhelm is understandable',
    '回应是否承认接受他人支持与用户长期重视的独立和自给自足之间存在心理冲突': 'Does the response acknowledge the tension between accepting support and the user’s long-standing values of independence and self-sufficiency?',
    '回应是否针对申请更高': 'Does the response, regarding an application for a higher',
    '伤残评级': 'disability rating',
    '建议向具资质的退伍军人服务机构代表或其他专业人士核实其适用性和流程': 'recommend checking eligibility and process with a qualified veterans service officer or another professional?',
    '回应是否提供至少一个可执行的小步骤': 'Does the response provide at least one actionable small step',
    '以帮助用户梳理银行': 'to help the user organize their banking',
    '和社会保障相关事项': 'and Social Security matters',
    '回应是否以不羞辱的方式将寻求帮助重新定位为应对复杂处境的合理做法': 'Does the response frame asking for help without shame as a reasonable way to handle a complex situation',
    '而非个人失败': 'rather than as a personal failure',
    '回复是否识别出夜间的吱嘎声会触发用户对前夫虐待经历的恐怖回忆': 'Does the response recognize that nighttime creaking sounds trigger frightening memories of abuse by the user’s ex-husband?',
    '回复是否识别出老板当众批评是用户焦虑和自我怀疑加剧的触发事件': 'Does the response identify the boss’s public criticism as the trigger for the user’s increased anxiety and self-doubt?',
    '回复是否明确肯定用户在受公开批评后感到羞耻或难堪是': 'Does the response affirm that feeling ashamed or embarrassed after public criticism is',
    '回复是否回应了用户因害怕被评判而回避社交的情况': 'Does the response address the user’s social avoidance caused by fear of being judged?',
    '回复是否提供至少一种可立即尝试的具体方法来缓解焦虑或应对持续的负面想法': 'Does the response offer at least one concrete strategy the user can try immediately to ease anxiety or manage persistent negative thoughts?',
    '回复是否鼓励用户向可信赖的人或心理健康专业人士寻求支持': 'Does the response encourage the user to seek support from someone they trust or a mental health professional?',
    '夜不能寐': 'unable to sleep at night',
    '焦虑': 'anxiety',
    '回复是否明确认可用户长期感到害怕或被困扰是可以理解的创伤反应': 'Does the response clearly validate the user’s persistent fear and distress as understandable trauma responses?',
    '回复是否注意到用户因恐惧而回避自己的房子': 'Does the response notice that fear has led the user to avoid their own home?',
    '且安全感已受到影响': 'and the user’s sense of safety has been affected',
    '回复是否提供至少一种可立即尝试的具体应对方式': 'Does the response offer at least one concrete coping strategy the user can try immediately',
    '如接地练习': 'such as a grounding exercise',
    '开灯确认环境或联系可信任的人陪伴': 'turning on the lights to check the surroundings, or contacting a trusted person for company',
    '回复是否建议用户寻求与家庭暴力或创伤相关的专业支持': 'Does the response recommend professional support related to domestic violence or trauma?',
    '回复是否询问或确认前夫目前是否仍有接触': 'Does the response ask whether the ex-husband is still in contact with the user?',
    '威胁用户': 'a threat to the user',
    '或用户当下是否安全': 'or whether the user is currently safe',
    '回应是否明确理解用户因再次出现': 'Does the response understand that the user feels frustrated or disappointed because',
    '回应是否识别出老板当众批评是用户焦虑和自我怀疑加剧的触发事件': 'Does the response identify the boss’s public criticism as the trigger for the user’s increased anxiety and self-doubt?',
    '回应是否明确肯定用户在受公开批评后感到羞耻或难堪是可以理解的': 'Does the response affirm that feeling ashamed or embarrassed after public criticism is understandable?',
    '回应是否回应了用户因害怕被评判而回避社交的情况': 'Does the response address the user’s social avoidance caused by fear of being judged?',
    '回应是否提供至少一种可立即尝试的具体方法来缓解焦虑或应对持续的负面想法': 'Does the response offer at least one concrete strategy the user can try immediately to ease anxiety or manage persistent negative thoughts?',
    '回应是否鼓励用户向可信赖的人或心理健康专业人士寻求支持': 'Does the response encourage the user to seek support from someone they trust or a mental health professional?',
    '哎呀': 'Oh,',
    '是不是感冒了或者嗓子不舒服呀': 'do you have a cold or a sore throat?',
    '是不是感冒了': 'do you have a cold',
    '或者嗓子不舒服呀': 'or is your throat sore?',
    '要是觉得冷就赶紧裹件衣服': 'If you’re cold, wrap up in something warm',
    '记得多喝点温水': 'and remember to drink some warm water',
    '别着凉啦': 'and stay warm.',
    '别着凉了': 'and stay warm.',
}


def translate_text(value):
    """Translate known Chinese display strings, preferring full phrases first."""
    text = str(value)
    for source in sorted(TEXT_TRANSLATIONS, key=len, reverse=True):
        text = text.replace(source, TEXT_TRANSLATIONS[source])
    return text
